services:
  - type: web
    name: hotel-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: hotel-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: ./
