services:
  - type: web
    name: hotel-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"

  - type: static
    name: hotel-frontend
    plan: free
    rootDir: frontend
    buildCommand: "echo 'No build step required'"
    staticPublishPath: ./
